[workspace]
resolver = "2"
members = [
    "hypertext-application-language",
    "pagination",
    "anserno-core",
    "calibre-data",
    "anserno",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Zachary Elliott <contact@zell.io>"]
license-file = "LICENSE"
