//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "books_authors_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub book: i32,
    pub author: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Author,
    Book,
    FlatBook,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Author => Entity::belongs_to(super::authors::Entity)
                .from(Column::Author)
                .to(super::authors::Column::Id)
                .into(),

            Self::Book => Entity::belongs_to(super::books::Entity)
                .from(Column::Book)
                .to(super::books::Column::Id)
                .into(),

            Self::FlatBook => Entity::belongs_to(super::flat_books::Entity)
                .from(Column::Book)
                .to(super::flat_books::Column::Id)
                .into(),
        }
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Author.def()
    }
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Book.def()
    }
}

impl Related<super::flat_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlatBook.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
