//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod authors;
pub mod books;
pub mod books_authors_link;
pub mod books_series_link;
pub mod comments;
pub mod data;
pub mod flat_books;
pub mod search_index;
pub mod series;
