//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::authors::Entity as Authors;
pub use super::books::Entity as Books;
pub use super::books_authors_link::Entity as BooksAuthorsLink;
pub use super::books_series_link::Entity as BooksSeriesLink;
pub use super::comments::Entity as Comments;
pub use super::data::Entity as Data;
pub use super::flat_books::Entity as FlatBook;
pub use super::search_index::Entity as SearchIndex;
pub use super::series::Entity as Series;
