//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::{entity::prelude::*, DeriveRelation, Related};
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "authors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub sort: Option<String>,
    pub link: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::books_authors_link::Entity")]
    BooksAuthorsLink,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksAuthorsLink.def()
    }
}

#[derive(Debug)]
pub struct AuthorsToBooks;

impl Linked for AuthorsToBooks {
    type FromEntity = Entity;
    type ToEntity = super::books::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            super::books_authors_link::Relation::Author.def().rev(),
            super::books_authors_link::Relation::Book.def(),
        ]
    }
}

impl ActiveModelBehavior for ActiveModel {}
