//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub sort: Option<String>,
    pub timestamp: Option<DateTimeUtc>,
    pub pubdate: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Double")]
    pub series_index: f64,
    pub author_sort: Option<String>,
    pub isbn: Option<String>,
    pub lccn: Option<String>,
    pub path: String,
    pub flags: i32,
    pub uuid: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub has_cover: Option<bool>,
    pub last_modified: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::books_authors_link::Entity")]
    BooksAuthorsLink,

    #[sea_orm(has_many = "super::books_series_link::Entity")]
    BooksSeriesLink,

    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,

    #[sea_orm(has_many = "super::data::Entity")]
    Formats,

    #[cfg(feature = "search")]
    #[sea_orm(has_one = "super::search_index::Entity")]
    SearchIndex,
}

impl Related<super::books_authors_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksAuthorsLink.def()
    }
}

impl Related<super::books_series_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksSeriesLink.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Formats.def()
    }
}

#[derive(Debug)]
pub struct BooksToAuthors;

impl Linked for BooksToAuthors {
    type FromEntity = Entity;
    type ToEntity = super::authors::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            super::books_authors_link::Relation::Book.def().rev(),
            super::books_authors_link::Relation::Author.def(),
        ]
    }
}

#[derive(Debug)]
pub struct BooksToSeries;

impl Linked for BooksToSeries {
    type FromEntity = Entity;
    type ToEntity = super::series::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            super::books_series_link::Relation::Book.def().rev(),
            super::books_series_link::Relation::Series.def(),
        ]
    }
}

#[cfg(feature = "search")]
impl Related<super::search_index::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SearchIndex.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
