//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod authors;
pub mod books;
pub mod books_authors_link;
pub mod books_series_link;
pub mod comments;
pub mod data;
pub mod series;

#[cfg(feature = "search")]
pub mod search_index;
