//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub sort: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::books_series_link::Entity")]
    BooksSeriesLink,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksSeriesLink.def()
    }
}

#[derive(Debug)]
pub struct SeriesToBooks;

impl Linked for SeriesToBooks {
    type FromEntity = Entity;
    type ToEntity = super::books::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            super::books_series_link::Relation::Series.def().rev(),
            super::books_series_link::Relation::Book.def(),
        ]
    }
}

impl ActiveModelBehavior for ActiveModel {}
