---
name: Publish Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-target:
          - toolchain: stable
            target: aarch64-unknown-linux-gnu
          - toolchain: stable
            target: aarch64-unknown-linux-musl
          - toolchain: stable
            target: x86_64-unknown-linux-gnu
          - toolchain: stable
            target: x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.build-target.toolchain }}
          targets: ${{ matrix.build-target.target }}
      - name: Install cross
        run: >-
          cargo install cross
      - name: Fetch rust dependencies
        run: >-
          cargo fetch --target ${{ matrix.build-target.target }}
      - name: Build release
        run: >-
          cross build --release --target ${{ matrix.build-target.target }} --bin anserno
      - name: Package release
        run: |-
          set -o errexit -o nounset -o pipefail -o xtrace

          mkdir release

          cp target/${{ matrix.build-target.target }}/release/anserno release/anserno-${{ matrix.build-target.target }}

          tar --create --directory anserno-core static templates --file - | gzip >release/anserno-assets.tar.gz

          cd release || exit 1

          sha256sum anserno-${{ matrix.build-target.target }} >anserno-${{ matrix.build-target.target }}.sha256sum
          sha256sum anserno-assets.tar.gz >anserno-assets.tar.gz.sha256sum
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: 'release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
